export const NavRoutes = [
  { href: "/", name: "Home" },
  { href: "/", name: "Landlord" },
  { href: "/", name: "Tenants" },
  { href: "/", name: "Contact us" },
];
export const PropertyItems = [
  // page 1
  {
    id: 1,
    image: "/images/property-1.jpg",
    title: "2578 Folsom Street, San Francisco, CA, 94110",
    type: "Private room",
    price: 1200,
    beds: 4,
    baths: 3,
    floors: 1,
  },
  {
    id: 2,
    image: "/images/property-2.jpg",
    title: "78 Lekki Street, San Francisco, CA, 2187",
    type: "Shared space",
    price: 800,
    beds: 5,
    baths: 5,
    floors: 1,
  },
  {
    id: 3,
    image: "/images/property-3.jpg",
    title: "278 Ogun Avenue, San Francisco, CA, 15491",
    type: "Shared space",
    price: 1500,
    beds: 1,
    baths: 5,
    floors: 1,
  },
  {
    id: 4,
    image: "/images/property-3.jpg",
    title: "25 Warri Street, San Francisco, CA, 41901",
    type: "Shared space",
    price: 800,
    beds: 5,
    baths: 5,
    floors: 1,
  },
  {
    id: 5,
    image: "/images/property-4.jpg",
    title: "578 Werey Street, San Francisco, CA, 1925",
    type: "Shared space",
    price: 800,
    beds: 5,
    baths: 5,
    floors: 1,
  },
  {
    id: 6,
    image: "/images/property-5.jpg",
    title: "25 Circle Avenue, San Francisco, CA, 2482",
    type: "Shared space",
    price: 800,
    beds: 5,
    baths: 5,
    floors: 1,
  },
  // page 2
  {
    id: 7,
    image: "/images/property-1.jpg",
    title: "25 Circle Avenue, San Francisco, CA, 2482",
    type: "Private room",
    price: 1200,
    beds: 4,
    baths: 3,
    floors: 2,
  },
  {
    id: 8,
    image: "/images/property-2.jpg",
    title: "78 Lekki Street, San Francisco, CA, 2187",
    type: "Shared space",
    price: 800,
    beds: 5,
    baths: 5,
    floors: 2,
  },
  {
    id: 9,
    image: "/images/property-3.jpg",
    title: "578 Werey Street, San Francisco, CA, 1925",
    type: "Shared space",
    price: 1500,
    beds: 1,
    baths: 5,
    floors: 2,
  },
  {
    id: 10,
    image: "/images/property-3.jpg",
    title: "25 Warri Street, San Francisco, CA, 41901",
    type: "Shared space",
    price: 800,
    beds: 5,
    baths: 5,
    floors: 2,
  },
  {
    id: 11,
    image: "/images/property-4.jpg",
    title: "278 Ogun Avenue, San Francisco, CA, 15491",
    type: "Shared space",
    price: 800,
    beds: 5,
    baths: 5,
    floors: 2,
  },
  {
    id: 12,
    image: "/images/property-5.jpg",
    title: "2578 Folsom Street, San Francisco, CA, 94110",
    type: "Shared space",
    price: 800,
    beds: 5,
    baths: 5,
    floors: 2,
  },
  // page 3
  {
    id: 13,
    image: "/images/property-1.jpg",
    title: "578 Werey Street, San Francisco, CA, 1925",
    type: "Private room",
    price: 1200,
    beds: 4,
    baths: 3,
    floors: 3,
  },
  {
    id: 14,
    image: "/images/property-2.jpg",
    title: "2578 Folsom Street, San Francisco, CA, 94110",
    type: "Shared space",
    price: 800,
    beds: 5,
    baths: 5,
    floors: 3,
  },
  {
    id: 15,
    image: "/images/property-3.jpg",
    title: "278 Ogun Avenue, San Francisco, CA, 15491",
    type: "Shared space",
    price: 1500,
    beds: 1,
    baths: 5,
    floors: 3,
  },
  {
    id: 16,
    image: "/images/property-3.jpg",
    title: "25 Circle Avenue, San Francisco, CA, 2482",
    type: "Shared space",
    price: 800,
    beds: 5,
    baths: 5,
    floors: 3,
  },
  {
    id: 17,
    image: "/images/property-4.jpg",
    title: "78 Lekki Street, San Francisco, CA, 2187",
    type: "Shared space",
    price: 800,
    beds: 5,
    baths: 5,
    floors: 3,
  },
  {
    id: 18,
    image: "/images/property-5.jpg",
    title: "25 Warri Street, San Francisco, CA, 41901",
    type: "Shared space",
    price: 800,
    beds: 5,
    baths: 5,
    floors: 3,
  },
];

export const TestimonyList = [
  {
    text: "Error odit! Laboriosam esse veritatis mollitia ullam repudiandae, neque sint expedita? Repellendus illo earum quibusdam expedita ipsam perferendis iste explicabo delectus magnam amet nulla quae itaque placeat, cumque autem. Consectetur eum laborum eligendi non ipsam molestias, voluptates maiores illo totam at hic soluta.",
    user: "Johnny Doe",
    image: "https://loremflickr.com/100/100/person",
    job: "CEO, OA Ltd",
  },
  {
    text: "Dicta sint iure nemo vitae id officiis facere neque ris obcaecati at tempore excepturi sed atque, doloremque animi totam placeat architecto. Nobis odit adipisci possimus voluptates nihil, rem dolore atque,  suscipit mollitia sed numquam harum.",
    user: "Fiifi Doe",
    image: "https://loremflickr.com/100/100/woman",
    job: "Clerk",
  },
  {
    text: "Mollitia ullam repudiandae, neque sint expedita? Repellendus illo earum quibusdam expedita ipsam perferendis iste explicabo delectus magnam amet nulla quae itaque placeat, cumque autem. Consectetur eum laborum eligendi non ipsam molestias, voluptates maiores illo totam at hic soluta sit, fuga, obcaecati nihil adipisci facilis eaque veniam.",
    user: "Peter Obi",
    image: "https://loremflickr.com/100/100/map",
    job: "UI/UX Designer",
  },
  {
    text: "Amet aut omnis labore culpa dicta sint iure nemo vitae id officiis facere neque ris obcaecati at tempore excepturi sed atque, doloremque animi totam placeat architecto. Nobis odit adipisci possimus voluptates nihil, rem dolore atque,  suscipit mollitia sed numquam harum.",
    user: "N. Akuffo Addo",
    image: "https://loremflickr.com/100/100/president",
    job: "Writer",
  },
];
